comments: store env variable
logconf:
  level: DEBUG
  name: crawl
  path: ./
  postfix: .log
  prefix: crun_
btyunso:
  domain: www.btyunsou.co
  scheme: http
  entryhtml: btmain.html
  samplehtm: entry.html
