comments: store env variable
logconf:
  level: DEBUG
  name: crawl
  path: ./
  postfix: .log
  prefix: crun_
btyunso:
  domain: www.btyunsou.co
  schema: http://
  method: get
  # http://www.btyunsou.co/search?kw=
  action: /search
  keyword: kw?

